<?php

define("BLOCK_NAVBUTTONS_HOME_FRONTPAGE", 1); 
define("BLOCK_NAVBUTTONS_HOME_COURSE", 2); 

define("BLOCK_NAVBUTTONS_FIRST_COURSE", 1); 
define("BLOCK_NAVBUTTONS_FIRST_IN_COURSE", 2); 
define("BLOCK_NAVBUTTONS_FIRST_IN_SECTION", 3);

define("BLOCK_NAVBUTTONS_LAST_COURSE", 1); 
define("BLOCK_NAVBUTTONS_LAST_IN_COURSE", 2); 
define("BLOCK_NAVBUTTONS_LAST_IN_SECTION", 3);

define("BLOCK_NAVBUTTONS_NEWWINDOW", 1);
define("BLOCK_NAVBUTTONS_SAMEWINDOW", 0);

define("BLOCK_NAVBUTTONS_HOMEICON", 0);
define("BLOCK_NAVBUTTONS_FIRSTICON", 1);
define("BLOCK_NAVBUTTONS_PREVICON", 2);
define("BLOCK_NAVBUTTONS_NEXTICON", 3);
define("BLOCK_NAVBUTTONS_LASTICON", 4);
define("BLOCK_NAVBUTTONS_EXTRA1ICON", 5);
define("BLOCK_NAVBUTTONS_EXTRA2ICON", 6);

?>

