<?php

define("BLOCK_NAVBUTTONS_HOME_FRONTPAGE", 1); 
define("BLOCK_NAVBUTTONS_HOME_COURSE", 2); 

define("BLOCK_NAVBUTTONS_FIRST_COURSE", 1); 
define("BLOCK_NAVBUTTONS_FIRST_IN_COURSE", 2); 
define("BLOCK_NAVBUTTONS_FIRST_IN_SECTION", 3);

define("BLOCK_NAVBUTTONS_LAST_COURSE", 1); 
define("BLOCK_NAVBUTTONS_LAST_IN_COURSE", 2); 
define("BLOCK_NAVBUTTONS_LAST_IN_SECTION", 3);

?>

